# House Price Prediction

## Problem statement

The real estate market is influenced by numerous factors such as location, size, number of bedrooms and bathrooms, neighborhood amenities, and economic conditions. Predicting house prices accurately is essential for various stakeholders including homebuyers, sellers, real estate agents, and investors.

## Importing libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# house pricing dataset
df = pd.read_csv('ParisHousing.csv')

In [3]:
df.head()

squareMeters  numberOfRooms  hasYard  hasPool  floors  cityCode  \
0         75523              3        0        1      63      9373   
1         80771             39        1        1      98     39381   
2         55712             58        0        1      19     34457   
3         32316             47        0        0       6     27939   
4         70429             19        1        1      90     38045   

   cityPartRange  numPrevOwners  made  isNewBuilt  hasStormProtector  \
0              3              8  2005           0                  1   
1              8              6  2015           1                  0   
2              6              8  2021           0                  0   
3             10              4  2012           0                  1   
4              3              7  1990           1                  0   

   basement  attic  garage  hasStorageRoom  hasGuestRoom      price  
0      4313   9005     956               0             7  7559081.5  
1      3653   2436     128               1             2  8085989.5  
2      2937   8852     135               1             9  5574642.1  
3       659   7141     359               0             3  3232561.2  
4      8435   2429     292               1             4  7055052.0

## 2. Data Preprocessing

In [4]:
df.shape

(10000, 17)

In [5]:
df.describe()

squareMeters  numberOfRooms       hasYard       hasPool        floors  \
count   10000.00000   10000.000000  10000.000000  10000.000000  10000.000000   
mean    49870.13120      50.358400      0.508700      0.496800     50.276300   
std     28774.37535      28.816696      0.499949      0.500015     28.889171   
min        89.00000       1.000000      0.000000      0.000000      1.000000   
25%     25098.50000      25.000000      0.000000      0.000000     25.000000   
50%     50105.50000      50.000000      1.000000      0.000000     50.000000   
75%     74609.75000      75.000000      1.000000      1.000000     76.000000   
max     99999.00000     100.000000      1.000000      1.000000    100.000000   

           cityCode  cityPartRange  numPrevOwners         made    isNewBuilt  \
count  10000.000000   10000.000000   10000.000000  10000.00000  10000.000000   
mean   50225.486100       5.510100       5.521700   2005.48850      0.499100   
std    29006.675799       2.872024       2.856667      9.30809      0.500024   
min        3.000000       1.000000       1.000000   1990.00000      0.000000   
25%    24693.750000       3.000000       3.000000   1997.00000      0.000000   
50%    50693.000000       5.000000       5.000000   2005.50000      0.000000   
75%    75683.250000       8.000000       8.000000   2014.00000      1.000000   
max    99953.000000      10.000000      10.000000   2021.00000      1.000000   

       hasStormProtector      basement        attic       garage  \
count       10000.000000  10000.000000  10000.00000  10000.00000   
mean            0.499900   5033.103900   5028.01060    553.12120   
std             0.500025   2876.729545   2894.33221    262.05017   
min             0.000000      0.000000      1.00000    100.00000   
25%             0.000000   2559.750000   2512.00000    327.75000   
50%             0.000000   5092.500000   5045.00000    554.00000   
75%             1.000000   7511.250000   7540.50000    777.25000   
max             1.000000  10000.000000  10000.00000   1000.00000   

       hasStorageRoom  hasGuestRoom         price  
count    10000.000000   10000.00000  1.000000e+04  
mean         0.503000       4.99460  4.993448e+06  
std          0.500016       3.17641  2.877424e+06  
min          0.000000       0.00000  1.031350e+04  
25%          0.000000       2.00000  2.516402e+06  
50%          1.000000       5.00000  5.016180e+06  
75%          1.000000       8.00000  7.469092e+06  
max          1.000000      10.00000  1.000677e+07

In [6]:
df.isnull().sum()

squareMeters         0
numberOfRooms        0
hasYard              0
hasPool              0
floors               0
cityCode             0
cityPartRange        0
numPrevOwners        0
made                 0
isNewBuilt           0
hasStormProtector    0
basement             0
attic                0
garage               0
hasStorageRoom       0
hasGuestRoom         0
price                0
dtype: int64

## 3. Split into feature and target

In [7]:
## Dividing the dataset into independent and dependent feature
feature = df.iloc[:,:-1]
target = df.iloc[:,-1]

In [8]:
feature.shape

(10000, 16)

In [9]:
target.shape

(10000,)

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

std_data = scaler.fit_transform(feature)
std_data

array([[ 0.89156241, -1.64351831, -1.01755405, ...,  1.53748782,
        -1.00601811,  0.63137326],
       [ 1.07395603, -0.39418009,  0.98274878, ..., -1.62237047,
         0.99401789, -0.9428096 ],
       [ 0.20303346,  0.26519286, -1.01755405, ..., -1.59565669,
         0.99401789,  1.26104641],
       ...,
       [ 1.18065352, -1.64351831, -1.01755405, ..., -0.79424336,
         0.99401789,  1.26104641],
       [ 0.31855868,  0.68163893, -1.01755405, ..., -0.81714088,
         0.99401789, -0.31313646],
       [-1.68318347,  1.16749268, -1.01755405, ..., -1.04993237,
         0.99401789,  0.31653669]])

In [11]:
feature = std_data

## 4. Train test split

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(feature,target,test_size=0.2,random_state=42)

In [13]:
print(X_train.shape,y_train.shape)

(8000, 16) (8000,)


In [14]:
print(X_test.shape,y_test.shape)

(2000, 16) (2000,)


## 5. Training Model

In [15]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()

In [16]:
lin_reg.fit(X_train,y_train)

LinearRegression()

## 6. Model Evaluation

In [17]:
from sklearn.metrics import r2_score
y_pred = lin_reg.predict(X_test)
r2_score(y_pred,y_test)

0.9999995780585409

## 7. Predictive System

In [22]:
input = np.array([4.9795000e+04, 1.9000000e+01, 0.0000000e+00, 0.0000000e+00,
       4.3000000e+01, 9.6569000e+04, 1.0000000e+01, 1.0000000e+00,
       2.0130000e+03, 1.0000000e+00, 0.0000000e+00, 8.5200000e+02,
       9.6040000e+03, 6.1900000e+02, 0.0000000e+00, 8.0000000e+00,]).reshape(1,-1)
std_input = scaler.transform(input)
price = lin_reg.predict(std_input)
price[0]

C:\Users\asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


4982639.157273832

In [48]:
df.iloc[6767].values

array([4.9795000e+04, 1.9000000e+01, 0.0000000e+00, 0.0000000e+00,
       4.3000000e+01, 9.6569000e+04, 1.0000000e+01, 1.0000000e+00,
       2.0130000e+03, 1.0000000e+00, 0.0000000e+00, 8.5200000e+02,
       9.6040000e+03, 6.1900000e+02, 0.0000000e+00, 8.0000000e+00,
       4.9832823e+06])

In [19]:
df.iloc[3421].values

array([1.6218000e+04, 6.6000000e+01, 1.0000000e+00, 1.0000000e+00,
       7.0000000e+01, 4.4999000e+04, 5.0000000e+00, 1.0000000e+01,
       2.0150000e+03, 1.0000000e+00, 1.0000000e+00, 6.6910000e+03,
       5.4800000e+02, 2.2000000e+02, 1.0000000e+00, 8.0000000e+00,
       1.6301485e+06])

In [21]:
input = np.array([1.6218000e+04, 6.6000000e+01, 1.0000000e+00, 1.0000000e+00,
       7.0000000e+01, 4.4999000e+04, 5.0000000e+00, 1.0000000e+01,
       2.0150000e+03, 1.0000000e+00, 1.0000000e+00, 6.6910000e+03,
       5.4800000e+02, 2.2000000e+02, 1.0000000e+00, 8.0000000e+00]).reshape(1,-1)
std_input = scaler.transform(input)
price = lin_reg.predict(std_input)
price[0]

C:\Users\asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


1632347.3903009188